### ISSUE TITLE
6 hrs and it still doesn't work

### ISSUE THREAD

**Issue by kwaneetum** [zanonmark/Google-4-TbSync#16]
I have been trying to get Google-4-TbSync to work for 6 hours now and . . . nothing. The last error message I got was:

Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (*************@gmail.com). [That's me]

I'm assuming that something is messed up with the Google API account but I have no way to check it. I followed the "directions" as well as I could but it was like completing a tax form in another language, where the necessary fields were highlighted in red and the rest were left incomprehensible.  If there isn't some way for normal users to set this up, the Add-on needs to be flagged as "Developers Only."

This is a badly needed addition to Thunderbird but, how does one get it set up?

Thanks

**Comment by zanonmark** [comment]
Thanks for Your report.

I'm sorry the procedure for getting the Google credentials is quite complex but, as stated in the ATN page, "if this seems complicated, please blame Google, not me...", as unfortunately I have no way to simplify it apart from writing a step-by-step howto (Yes, the red fields are the only ones You should concentrate on, the rest may be left as they are).
And I can't provide an add-on with pre-built credentials because Google doesn't allow so.

That error seems to indicate that You did not enable the account You're trying to retrieve contacts from.
I.e.: if You're synchronizing with info@example.com, You must add info@example.com in the "Test users" step of my howto.

Could You please check again and report back?

Thanks,
MZ

**Comment by zanonmark** [comment]
I agree that part of the howto was not perfectly clear, because You're not the only one having this issue.
So I just made a slight modification.

Thanks,
MZ

**Comment by zanonmark** [comment]
Is there any news on this issue? Were You successful with the latest instructions?

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
