### ISSUE TITLE
Weird "404 error" on sync

### ISSUE THREAD

**Issue by saleslogistix** [zanonmark/Google-4-TbSync#17]
One of my contact lists (with only 400 contacts and 22 distribution lists) has an intermittently repeatable issue. Almost immediately upon sync, it fails with a 404 error issued by Google.  I haven't changed the configuration of either Tbird or Google, but I have been making updates on both sides.  To make it go away, I disabled/re-established sync and it worked. But then a few days later, it returned.
One hyptothesis: When Tbird has a distribution list that doesn't exist as a Google label:  _sort of_ makes sense...but only if you really think about it. But it's super easy to fall into the trap, if you rename one of your Google labels.  To test this hypothesis, I edited the distribution lists so they agreed with the Google labels, but it still fails the same way.
Is there a way to turn on more verbose logging so I can provide you more useful information?

**Comment by saleslogistix** [comment]
Oh...another clue:  when I use the Test Connection button, it indicates OK and shows the correct number of contacts but the number of "contact groups" is shown as 22, where the number of labels/distlists is 14.  Are there some invisible entities being counted?
When I push the same button on one of my other contact lists that has no labels/distlists, the result shows 8 "contact groups" (maybe these are google defaults like "my contacts, my favorites" etc. Might be better to always subtract those default contact groups out...

**Comment by zanonmark** [comment]
Thanks for Your report.

First, renaming contact groups / distribution lists / mailing-lists shouldn't be an issue, because the synchronization is done using the internal ID, not the display name.

As for the log, You can attach the full log found in the Debug console.
Please contact me privately (info@marcozanon.com) before doing so, because there might be sensitive data to be cleared.

As for the difference in the contact group count, You got it right: the "Test" button also includes the System Contact Groups ("My contacts", "My co-workers", "My family", etc.).
I'm not sure subtracting 8 from the total count is a wise choice, because I'm not sure they will always be 8.
I could loop on the list, but this would take some time.
Or I could simply add a "including system contact groups" statement :)

I'm waiting for Your email privately then.

Thanks,
MZ

**Comment by zanonmark** [comment]
As per private communication, the bug is now fixed - for contact groups too.
Thanks for the perfect bug reporting.

I'm keeping this open to fix the output message in the "Test connection" button.

Thanks,
MZ

**Comment by zanonmark** [comment]
Fixed the output message too.

Thanks,
MZ
