### ISSUE TITLE
Sync wipes out TB fields address fields Google doesn't know about

### ISSUE THREAD

**Issue by saleslogistix** [zanonmark/Google-4-TbSync#19]
Ho boy is this one a show-stopper for me.  Just discovered that a whole bunch of my data gets wiped on each sync.
Config: Win10 64 bit pro, TB 78.13.0 (altho this has been around a while), G4TBsync 0.1.8, TBsync 2.22
Using both two-way and one way sync, here's the issue.
Look at an TB address book entry -- all works fine for the Contact, Private, Work, Chat, and Proto tabs.
Now look at the Other tab, where there are four "Custom" fields, and those aren't replicated in Google.
In the old days of gContactSync, those fields were left alone even as all others were updated.
But your model, any time an update happens from Google, those fields just get erased.
Those fields are extremely useful for data that you want to hide from Google.
I'm guessing what you do is throw out the entire TB "card" and replace it with updated info from Google...but what you need to do is copy the contents of the custom fields before you erase the card, then re-instate them once the card exists again.
Of course, it won't be that simple...

**Comment by zanonmark** [comment]
Thanks for Your ticket.
However, everything seems to be working as expected.

As far as I know, "Custom" fields in Thunderbird aren't meant to be "private" data managed by Thunderbird only.
As far as my algorithm is concerned, the "Custom" Thunderbird fields are set with the "User defined" Google field values, or left blank if these are not defined (see AddressBookSynchronizer.js, from line 800).

I don't know if / why gContactSync had a different behaviour, but this one makes sense to be: trying to map Google-to-Thunderbird (and viceversa) as much as possible.

I'm closing this issue because I feel I have nothing to work on here, but feel free to reopen in case something is not clear.

Thanks,
MZ
