### ISSUE TITLE
Cannot sync categories aka labels

### ISSUE THREAD

**Issue by xtrailrunner** [zanonmark/Google-4-TbSync#4]
I would like to sync my Google address book including labels with my TB address book. I have installed the newest version of Google-4-TbSync and TbSync 2.21. I can sync my contacts but no labels or categories are created locally.
The software seems to be in a very early stage. Do I need category manager plug-in too or it is better to remove it from the installation? What is your recommendation? 
Regards Juergen

**Comment by zanonmark** [comment]
Hi,

the software is indeed in an early stage, but the label synchronization should be working - they are imported as "mailing lists" in Thunderbird.
What is not working at the moment is the Thunderbird-to-Google synchronization for the group memberships, i.e.: if you add a contact to a group in Thunderbird, this change is not replicated to Google.

Please check the latest version. I just included a "read-only mode" (Google-to-Thunderbird only synchronization), which I strongly suggest to use.

If the issue persists, feel free to comment here.

The Category Manager add-on is irrelevant to me.

Thanks,
MZ

**Comment by xtrailrunner** [comment]
Sorry to say that, but labels were not synced.
What I have done:
- deactivated category manager in Thunderbird
- downloaded newest version (read-only) and imported it as xpi file in Thunderbird
- switched off adress book synchronization in TbSync => my old adress book was removed
- switched on adress book synchronization in TbSync => all contacts were synced but neither mail lists nor labels are visible 

Regards Juergen

**Comment by zanonmark** [comment]
Thanks for Your additional information. All You did is indeed correct.

Could You please check the "include system contact groups" flag too? This enables synchronization with the "Family", "Friends", "Coworkers", "Starred" etc. Google default contact groups (which are deprecated by Google and are read-only on server side).

But, even if You leave it disabled, it should still synchronize all the other contact groups (if You have any, of course).

Could You please do this test for me and report here?

Thanks,
MZ

**Comment by xtrailrunner** [comment]
Where should I set the flag? On the desktop there is no option in Google Contacts. On the phone I can see the four system groups but they are all empty. 
I'm still confused about the terms "groups" and "labels". In Google contacts I have defined several labels. 
Regards Juergen

**Comment by zanonmark** [comment]
"Labels" on Google Contacts = "Contact groups" in Google People API terminology = "Mailing list contacts" on Thunderbird (!)
I decided to stick to the Google People API terminology.

When You create (or edit) a Google account in TbSync, You have 4 fields:
* Client ID
* Client secret
* Include system contact groups
* Read-only mode

The 3rd one is for synchronizing the Google groups too: "My Contacts", "Friends", "Coworkers", etc..
I set this as an external option because system groups are deprecated (they will be removed by Google in a while) and can't be updated back to Google (i.e. they are read-only on Google side); so hopepfully they will be soon gone.

Anyway, if You already set Your specific groups (labels), You should at least be synchronizing these ones.
So, it sounds like a bug.

First question: could You please tell me the names of those contact groups (labels)?

Thanks,
MZ

**Comment by zanonmark** [comment]
![option](https://user-images.githubusercontent.com/13437344/113481392-a4c1bf00-9499-11eb-8945-b3320dfc2928.png)

**Comment by xtrailrunner** [comment]
Thanks. Now I see the big difference.
For me the account settings look very different:

![grafik](https://user-images.githubusercontent.com/1944927/113484520-063d5a00-94a9-11eb-9947-378f82a60fe0.png)

**Comment by xtrailrunner** [comment]
Thanks. Now I see where the problem is.
I have used my existing TbSync Account ( CalDAV, CardDAV server) and checked the Address Book for Synchronization. This is obviously not working as expected.
What is you recommendation:
- Should I create a new acount for both calendar and contact data based on Google's people API or should I retain my CalDAV/CardDAV account for calendar data and create a separate account for contact data based on Google's People API?
- If I create a new account based on Google's people API which account name I should use. I cannot use the same name twice.
As you can see I'm a bit confused about the different APIs.

**Comment by zanonmark** [comment]
Thanks for updating back.

To clarify:

Google has currently 3 ways to make contact synchronizations:

1) Through the CardDAV protocol.
This should be the preferred choice, because it's a standard protocol and there are many interfaces (for example, the CalDAV and CardDAV provider You were using).
But the support by Google is broken, because it doesn't support synchronizing contact groups aka labels.
So, this is a no-go unless Google fixes it (which is: never, as the ticket has been open for years).

2) Through the Google Contacts API.
This is what gContactSync was doing.
But:
a) the user interface part of gContactSync is now broken, and will probably not be updated;
b) even if it was, the Google Contacts API itself is deprecated and will stop working on June 15th 2021.

And this leads us to the last method,
3) Through the Google People API.
This is exactly what my Google-4-TbSync add-on is doing.
Synchronization works well except for updating back contact group modifications (i.e.: if You add / delete an item in a mailing-list in Thunderbird, this will not be reported back to Google). I can't fix it at the moment because the current version of TbSync doesn't offer me the tools to do so, but this will be overcome after the TbSync rewrite to the new WebExtension standard (in a few weeks?).
So You'd better stick to the read-only mode: do Your modifications on Google and then let Google-4-TbSync synchronize them from Google to Thunderbird.

Hope it helps.

I consider the bug closed then.

Thanks,
MZ

**Comment by xtrailrunner** [comment]
Hi,
thank you for clarification.
But as a user my main question is still open. If I want to synchronize both calendar and contact data can I use the same account in TbSync or should I use two separate accounts? If I would need to have two separate accounts in TbSync can I choose the account name or should it be the same like the Google user account name? 
Regards Juergen

**Comment by zanonmark** [comment]
The contact synchronization already works 2-way, and so does the contact group one.
I.e.: You can create / edit / delete contacts or contact groups locally, and these changes will be replicated on Google (provided You didn't flag the "Read-only mode", obviously).

What doesn't work right now is that modifying a local contact group (= mailing-list) content cannot be replicated on Google.
But that happens on CardBook too, because mailing-lists simply aren't created, due to the Google bug in the CardDAV support.

So, to summarize:
* whichever add-on You decide to use, You're strongly suggested to use the "Read-only mode" provided by that add-on if available, because the TB structure is very poor compared to the Google one and You risk losing data if You synchronize them back;
* if You only want to synchronize contacts, in read-only or in read-write mode, You can use CardBook or Provider for CalDAV/CardDAV and stick to the CardDAV protocol, or You can use Google-4-TbSync and stick to the Google People API (gContactSync is no longer an option);
* if You also want to fully synchronize contact groups and their content, You must wait for the final version of Google-4-TbSync.

Hope it helps.

Thanks,
MZ
