### ISSUE TITLE
Add support for Calendar

### ISSUE THREAD

**Issue by Bigoukun** [zanonmark/Google-4-TbSync#44]
Hello,

Unlike the previous method, back when we could use "Provider for CalDAV & CardDAV" for TbSync to get our AdressBook from Google, we could also sync our agenda with Google Calendar. Maybe add that possibility in the future?

**Comment by zanonmark** [comment]
Hi,

Google-4-TbSync (which is a different add-on than "Provider for CalDAV & CardDAV") is currently focused on supporting Contacts only, and will probably be in the future too.

That's because for Calendar You can use any standard CalDAV connector, like the one provided with Thunderbird itself.
(This is not possible for Contacts, because the CardDAV support by Google is not perfect... hence the need for Google-4-TbSync.)

Thanks,
MZ
