### ISSUE TITLE
Questions about synced account

### ISSUE THREAD

**Issue by BillH99999** [zanonmark/Google-4-TbSync#48]
I successfully created my Google Cloud account and synced my Google Contacts to Thunderbird.  Thanks for the very explicit instructions.  They worked like a charm.  I do have a couple of questions however.

If I click on the account name in the account list pane, it does show the right number of entries (contacts + groups).  There is a group (label) under the account called myContacts.  It only includes about half of my contacts.  Why doesn't it show all my contacts? 

There are some labels that I don't use that show up under the account (all, blocked, chatBuddies, coworkers, family, friends).  I clicked on the 2 dots on the right and selected delete.  They seemed to get deleted.  However, they came back.  These labels (groups) are not defined in Google Contacts that I can see.  How can I remove them in Thunderbird since using delete didn't work.

Thanks,
Bill

**Comment by zanonmark** [comment]
Hi,

You are referring to the so-called "system groups", which is, standard groups created by Google.

In order not to include them, just uncheck the "Include system contact groups" option in Google-4-TbSync (You will have to disable the account first, then change the option and re-enable the account).
Google has deprecated those system groups, so not including them is the right choice.

You cannot directly remove them in Thunderbird and then synchronize the change back to Google because those groups are read-only (You cannot delete them in the server).

MZ

**Comment by zanonmark** [comment]
Oh, about the "myContacts" not showing all of Your real contacts: I don't know :)
Maybe the excluded ones have no email address?

MZ

**Comment by BillH99999** [comment]
Unchecking "Include system contact groups" did the trick.  I was confused about what this option did.  I thought I had to select it to get the groups I had created in Google Contacts.  Now I understand what it is doing.

I think you are absolutely correct on myContacts.  The ones missing do seem to be the ones without email addresses.

Thanks!
Bill
