### ISSUE TITLE
Having trouble synching Google labels to TB mailing lists

### ISSUE THREAD

**Issue by saleslogistix** [zanonmark/Google-4-TbSync#5]
Running TB 78.9 and TBsync 2.21 and Provider for Google 0.1 on Windows 10.
Have three accounts synching, all seem to work OK...except...I have one account that has ~400 contacts in it and 14 groups. All the contacts sync, all the labels appear on the TB side, but only three of the labels (mailing lists) are fully populated, and one of them is only partially populated.  
100% reproducible on my system.
(If you want to try it on your system, I can give you access).
Label names are 
(PLMWC)   CA-Waterboard List
(PLMWC) Customer Emails
(PLMWC) External Resources
PLMWC Cedar+RR
PLMWC LMtPine
PLMWC LPalo
PLMWC Madrone
PLMWC NoEmail
PLMWC Oak Knoll
PLMWC Toyon
PLMWC UMtPine
PLMWC UPalo
PLMWC Walnut
PLMWC Willow

**Comment by zanonmark** [comment]
Thanks for reporting.

Before we continue to investigate: maybe the contacts which weren't added to the TB mailing-lists have no email addresses?
If so, everything's fine because You can't add an email-less contact in a mailing-list.
If You still want to do so, please check the "Use fake email addresses" flag: a fake email address is created when synchronizing from Google to Thunderbird (and it will not be updated back to the Google server when synchronizing the opposite way).

Please let me know.

Thanks,
MZ

**Comment by saleslogistix** [comment]
You identified the issue!
Not a bug...PEBCAK...

**Comment by zanonmark** [comment]
No problem mate (I had to google for PEBCAK lol...)

Thanks, closing,
MZ
